version: "3.9"

services:
  app:
    build:
      context: .
    # ports:
    #   - "3003:3003"
    expose:
      - 8000
    volumes:
      - ./Notes:/Notes
      - notes-htmx_static_volume:/Notes/staticfolder
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn Notes.wsgi:application --bind '0.0.0.0:8000'"
    env_file:
      - Notes/.env
    depends_on:
      - db
    networks:
      - NotesHtmxNetwork

  db:
    image: postgres:13-alpine
    env_file:
      - Notes/.env
    expose:
      - 5436
    volumes:
    - my-volume:/var/lib/postgresql/data
    networks:
      - NotesHtmxNetwork

  nginx:
    build: ./nginx
    ports:
      - 3003:80
    depends_on:
      - app
    volumes:
      - notes-htmx_static_volume:/Notes/staticfolder
    networks:
      - NotesHtmxNetwork

volumes:
  my-volume:
  notes-htmx_static_volume:

networks:
  NotesHtmxNetwork:
    driver: bridge