# Generated by Django 4.1.6 on 2023-02-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
